[phases.setup]
nixPkgs = ["ruby_3_3", "postgresql"]

[phases.install]
cmds = ["cd backend && bundle install"]

[phases.build]
cmds = ["cd backend && bundle exec rails assets:precompile"]

[start]
cmd = "cd backend && bundle exec rails db:migrate && bundle exec puma -C config/puma.rb"
